[package]
name = "roblox-channel-bruteforcer"
version = "1.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
enable-ansi-support = "0.2.1"
reqwest = "0.11.17"
structopt = "0.3.26"
termcolor = "1.2.0"
tokio = { version = "1.28.1", features = ["full"] }
